Added kilojoules property to ingredient model (Issue #568)
wger-project/wger pull request #577
Opened 2020-12-13 02:07 UTC by nopinter

### Proposed Changes

  - added "energy_kilojoule" property to Ingredient class in wger/nutrition/models.py

  - added kilojoules to display on ingredient details page in wger/nutrition/templates/ingredient/view.html

  - added to wger/nutrition/static/js/nutrition.js, making kilojoules responsive to updates in ingredient amount according to user input

  - added test to wger/nutrition/tests/test_ingredient.py, verifying correct kilojoule conversion

### Please check that the PR fulfills these requirements

- [✓] Tests for the changes have been added (for bug fixes / features)
- [✓] New python code has been linted with with flake8 (``flake8 --config .github/linters/.flake8``)
and isort (``isort``) 
- [✓] Added yourself to AUTHORS.rst

### Other questions

* Does this PR introduce a breaking change such as a database migration? (i.e.
what changes might users need to make in their running application due to
this PR?) 

No

2020-12-13 02:12 UTC, nopinter commented
I worked on these changes with my partner, @derekli17, which is why his name is also included in AUTHORS.rst. We are currently undergraduates studying computer science, so if you have any feedback or want us to make changes, please feel free to let us know! Thanks.

2020-12-13 12:32 UTC, rolandgeider requested changes

2020-12-13 12:32 UTC, rolandgeider commented on wger/nutrition/models.py
> +            return self.energy * 4184
Sorry, 1kcal ist 4.1 kJ, not four thousand! :D I had just copy pasted it from the German wikipedia and hadn't thought that not everybody uses commas for this

2020-12-13 12:32 UTC, rolandgeider commented on wger/nutrition/models.py
> +    energy_kilojoule = property(_get_energy_kilojoule)
You can just define the property directly

```python
@property
def energy_kilojoule(self):
    if self.energy:
    ...
```

2020-12-13 12:34 UTC, rolandgeider commented
While showingeverywhere both the kcal and the kJ would break the UI flow, I'd add them to the nutrition list and the nutritional data table under the plan, then this would be ready to merge

2020-12-14 03:45 UTC, nopinter commented
Hi, thanks for your feedback! We've implemented your suggested changes. We found the "4,184" / "4.184" issue very funny, but that now is fixed 👍 . Additionally, we wanted your feedback on an aesthetic issue, which we've attached a picture of. 

<img width="825" alt="Screen Shot 2020-12-13 at 10 30 05 PM" src="https://user-images.githubusercontent.com/37446499/102038128-6ee6b680-3d94-11eb-93d5-fdd707607dfe.png">

As you can see in the red circle, sometimes the kilojoules wrap around onto the next line. Let us know your thoughts on this. We'd be more than willing to change some of the HTML/CSS to make it look cleaner if necessary.

2020-12-14 12:01 UTC, rolandgeider commented
I also had to laugh when I opened a plan and saw like half a million kJ 😂

And as for the line wrapping issue, we can save some space by removing the decimal place but other than that I wouldn't change much

2020-12-14 18:51 UTC, rolandgeider approved these changes

2020-12-15 00:16 UTC, nopinter commented
We have experimented with removing the decimal place, but we are still observing the line wrapping issue. We didn't make any further changes for this reason

2020-12-15 06:37 UTC, nopinter commented
Also, we would be willing to take #581 instead of #575 ! I'll will comment on those to reflect this

2020-12-15 15:43 UTC, rolandgeider approved these changes

2020-12-15 15:44 UTC, merged

2020-12-15 15:44 UTC, rolandgeider commented
Merged, thanks!!